# Site settings
title: My First Blog Entry
header-img: img/home-bg.png
email: tahseenfatima1986@gmail.com
copyright_name: tahseen447
description: > # this means to ignore newlines until "baseurl:"
  book log
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  tahseen447
learn_profile: tahseen447
email_username: tahseenfatima1986@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]

theme: jekyll-theme-minimal