# Site settings
author: Tahseen Siddiqui
title: Tahseen Siddiqui 
header-img: img/home-bg.png
email: tahseenfatima1986@gmail.com
copyright_name: Tahseen Siddiqui
description: > # this means to ignore newlines until "baseurl:"
  Woman, coder, mother, learner.... 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  tahseen447

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
